services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - db

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nch-dev
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
