/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Scope = "individual" | "organization" | "superadmin";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Gallery {
	id: string;
	publicUrl: string;
	sourceId: string | null;
}

export interface Socials {
	data: Generated<Json | null>;
	id: string;
	userId: string | null;
}

export interface Tags {
	id: string;
	isEventTag: Generated<boolean | null>;
	isOrganizationTag: Generated<boolean | null>;
	isUserTag: Generated<boolean | null>;
	tag: string;
}

export interface UserGallery {
	id: string;
	itemId: string | null;
	userId: string | null;
}

export interface Users {
	affiliatedOrganization: string | null;
	bio: string | null;
	city: string;
	country: string;
	createdAt: Generated<Timestamp>;
	email: string;
	emailVerificationExpiryTime: Timestamp | null;
	emailVerificationToken: string | null;
	expertise: string | null;
	fullName: string;
	gender: string;
	id: string;
	isActive: Generated<boolean | null>;
	isEmailVerified: Generated<boolean | null>;
	password: string;
	phoneNumber: string | null;
	profession: string | null;
	profileImage: string | null;
	province: string;
	requiresPasswordChange: Generated<boolean | null>;
	resetPasswordExpiryTime: Timestamp | null;
	resetPasswordToken: string | null;
	scope: Generated<Scope | null>;
	slug: string;
	updatedAt: Generated<Timestamp>;
}

export interface UserTags {
	id: string;
	tagId: string | null;
	userId: string | null;
}

export interface DB {
	gallery: Gallery;
	socials: Socials;
	tags: Tags;
	user_gallery: UserGallery;
	user_tags: UserTags;
	users: Users;
}
